version: '3'

services:
  webapplication1:
    image: webapplication1
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile


  webapplication2:
    image: webapplication2
    build:
      context: ./WebApplication2
      dockerfile: Dockerfile
